In [92]:
import numpy as np
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt
from collections import Counter
from itertools import combinations

In [93]:
data = pd.read_csv('movie_bd_v5.csv')
data.sample(5)

,imdb_id,budget,revenue,original_title,cast,director,tagline,overview,runtime,genres,production_companies,release_date,vote_average,release_year
1651,tt0335121,25000000,30114487,Godsend,Greg Kinnear|Rebecca Romijn|Robert De Niro|Cam...,Nick Hamm,"When a miracle becomes a nightmare, evil is born.",A couple agree to have their deceased son clon...,102,Drama|Horror|Science Fiction|Thriller,Lions Gate Films|2929 Productions|Artists Prod...,4/30/2004,4.7,2004
906,tt0166813,80000000,122563539,Spirit: Stallion of the Cimarron,Matt Damon|James Cromwell|Daniel Studi|Chopper...,Kelly Asbury|Lorna Cook,Leader. Hero. Legend.,As a wild stallion travels across the frontier...,83,Western|Animation|Adventure|Comedy|Family,DreamWorks Animation,5/24/2002,7.1,2002
477,tt1027718,70000000,134748021,Wall Street: Money Never Sleeps,Michael Douglas|Shia LaBeouf|Josh Brolin|Carey...,Oliver Stone,Gordon never gives up.,As the global economy teeters on the brink of ...,133,Drama|Crime,Twentieth Century Fox Film Corporation|Dune En...,9/2/2010,5.8,2010
1626,tt0299172,110000000,103951461,Home on the Range,Randy Quaid|Steve Buscemi|Judi Dench|Cuba Good...,Will Finn|John Sanford,Bust a Moo.,The Little Piece of Heaven family farm is abou...,76,Western|Animation|Family|Comedy|Music,Walt Disney Pictures|Walt Disney Feature Anima...,4/2/2004,5.8,2004
287,tt0892782,175000000,381509870,Monsters vs Aliens,Seth Rogen|Reese Witherspoon|Hugh Laurie|Paul ...,Rob Letterman|Conrad Vernon,"When aliens attack, monsters fight back.",When Susan Murphy is unwittingly clobbered by ...,94,Animation|Family|Adventure|Science Fiction,DreamWorks Animation,3/19/2009,6.0,2009

In [94]:
data.describe()

             budget       revenue      runtime  vote_average  release_year
count  1.889000e+03  1.889000e+03  1889.000000   1889.000000   1889.000000
mean   5.431083e+07  1.553653e+08   109.658549      6.140762   2007.860773
std    4.858721e+07  2.146698e+08    18.017041      0.764763      4.468841
min    5.000000e+06  2.033165e+06    63.000000      3.300000   2000.000000
25%    2.000000e+07  3.456058e+07    97.000000      5.600000   2004.000000
50%    3.800000e+07  8.361541e+07   107.000000      6.100000   2008.000000
75%    7.200000e+07  1.782626e+08   120.000000      6.600000   2012.000000
max    3.800000e+08  2.781506e+09   214.000000      8.100000   2015.000000

# Предобработка

In [95]:
answers = {} # создадим словарь для ответов

# тут другие ваши предобработки колонок например:

#the time given in the dataset is in string format.
#So we need to change this in datetime format
# ...

#Добавляем дополнительный столбец для дальнейших вычислений
data['profit']= data['revenue']-data['budget']
data['profit']

0       1363528810
1        228436354
2        185238201
3       1868178225
4       1316249360
           ...
1884      82299717
1885      -8444012
1886     -40865180
1887      -3962091
1888      -9782502
Name: profit, Length: 1889, dtype: int64

In [96]:
#Для задания 9 создадим уменьшенную версию датафрейма с данными только за 2008 год
data2008=data[data['release_year']==2008]
data2008

,imdb_id,budget,revenue,original_title,cast,director,tagline,overview,runtime,genres,production_companies,release_date,vote_average,release_year,profit
599,tt0468569,185000000,1001921825,The Dark Knight,Christian Bale|Michael Caine|Heath Ledger|Aaro...,Christopher Nolan,Why So Serious?,Batman raises the stakes in his war on crime. ...,152,Drama|Action|Crime|Thriller,DC Comics|Legendary Pictures|Warner Bros.|Syncopy,7/16/2008,8.1,2008,816921825
600,tt0910970,180000000,521311860,WALLÂ·E,Ben Burtt|Elissa Knight|Jeff Garlin|Fred Willa...,Andrew Stanton,An adventure beyond the ordinar-E.,WALLÂ·E is the last robot left on an Earth tha...,98,Animation|Family,Walt Disney Pictures|Pixar Animation Studios,6/22/2008,7.6,2008,341311860
601,tt0371746,140000000,585174222,Iron Man,Robert Downey Jr.|Terrence Howard|Jeff Bridges...,Jon Favreau,Heroes aren't born. They're built.,"After being held captive in an Afghan cave, bi...",126,Action|Science Fiction|Adventure,Marvel Studios,4/30/2008,7.3,2008,445174222
602,tt0936501,25000000,226830568,Taken,Liam Neeson|Famke Janssen|Maggie Grace|Katie C...,Pierre Morel,They took his daughter. He'll take their lives.,"While vacationing with a friend in Paris, an A...",93,Action|Thriller|Crime,Twentieth Century Fox Film Corporation|M6 Film...,2/18/2008,7.2,2008,201830568
603,tt0367882,185000000,786636033,Indiana Jones and the Kingdom of the Crystal S...,Harrison Ford|Cate Blanchett|Shia LaBeouf|Ray ...,Steven Spielberg,The adventure continues . . .,"Set during the Cold War, the Soviets â€“ led b...",122,Adventure|Action,Lucasfilm|Paramount Pictures,5/21/2008,5.6,2008,601636033
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
715,tt0858479,7000000,10569964,Smart People,Dennis Quaid|Sarah Jessica Parker|Ellen Page|T...,Noam Murro,Sometimes the smartest people have the most to...,Professor Lawrence Wetherhold (Dennis Quaid) m...,95,Comedy|Drama|Romance,Miramax Films|Sherazade Film Development|Groun...,4/11/2008,5.5,2008,3569964
716,tt0410377,37000000,100076342,Nim's Island,Abigail Breslin|Jodie Foster|Gerard Butler|Mic...,Jennifer Flackett|Mark Levin,Your adventure starts here.,A young girl inhabits an isolated island with ...,96,Adventure|Comedy|Family|Fantasy,Walden Media,4/3/2008,5.5,2008,63076342
717,tt0465502,25000000,30000000,Igor,John Cusack|Myleene Klass|Robin Walsh|Matt McK...,Anthony Leondis,All men aren't created Evil.,Animated fable about a clichÃ© hunchbacked evi...,87,Animation|Comedy|Family|Fantasy,Exodus Film Group|Exodus Productions,9/19/2008,5.4,2008,5000000
718,tt0455538,27000000,17286299,How to Lose Friends & Alienate People,Kelan Pannell|Janette Scott|Simon Pegg|Megan F...,Robert B. Weide,"He's across the pond, and out of his depth.",A British writer struggles to fit in at a high...,110,Comedy|Romance|Drama,UK Film Council|Intandem Films|Aramid Entertai...,10/2/2008,6.0,2008,-9713701
719,tt0494652,35000000,43650785,Welcome Home Roscoe Jenkins,Martin Lawrence|James Earl Jones|Margaret Aver...,Malcolm D. Lee,Roscoe Jenkins aims for the heartstrings and f...,"Martin Lawrence leads an all-star cast, includ...",114,Comedy|Drama,Universal Pictures|Spyglass Entertainment,2/8/2008,6.1,2008,8650785

In [97]:
#создадим функцию для преобразования и подсчёта данных, разделённых символом "|"
def splitter(series):
    list = []
    for string in series:
        for item in string.split('|'):
            list.append(item)
    return Counter(list)

# 1. У какого фильма из списка самый большой бюджет?

Использовать варианты ответов в коде решения запрещено.    
Вы думаете и в жизни у вас будут варианты ответов?)

In [98]:
# в словарь вставляем номер вопроса и ваш ответ на него
# Пример: 
answers['1'] = '2. Spider-Man 3 (tt0413300)'
# запишите свой вариант ответа
answers['1'] = '...'
# если ответили верно, можете добавить комментарий со значком "+"

In [99]:
data[data['budget']==data['budget'].max()]

,imdb_id,budget,revenue,original_title,cast,director,tagline,overview,runtime,genres,production_companies,release_date,vote_average,release_year,profit
723,tt1298650,380000000,1021683000,Pirates of the Caribbean: On Stranger Tides,Johnny Depp|PenÃ©lope Cruz|Geoffrey Rush|Ian M...,Rob Marshall,Live Forever Or Die Trying.,Captain Jack Sparrow crosses paths with a woma...,136,Adventure|Action|Fantasy,Walt Disney Pictures|Jerry Bruckheimer Films|M...,5/11/2011,6.3,2011,641683000

In [159]:
answers['1'] = 'Pirates of the Caribbean: On Stranger Tides (tt1298650)'

ВАРИАНТ 2

In [101]:
# можно добавлять разные варианты решения

# 2. Какой из фильмов самый длительный (в минутах)?

In [102]:
# думаю логику работы с этим словарем вы уже поняли, 
# по этому не буду больше его дублировать
answers['2'] = 'Gods and Generals (tt0279111)'

In [103]:
data[data['runtime']==data['runtime'].max()]

,imdb_id,budget,revenue,original_title,cast,director,tagline,overview,runtime,genres,production_companies,release_date,vote_average,release_year,profit
1157,tt0279111,56000000,12923936,Gods and Generals,Stephen Lang|Jeff Daniels|Robert Duvall|Kevin ...,Ronald F. Maxwell,The nations heart was touched by...,The film centers mostly around the personal an...,214,Drama|History|War,Turner Pictures|Antietam Filmworks,2/21/2003,5.8,2003,-43076064

# 3. Какой из фильмов самый короткий (в минутах)?

In [104]:
data[data['runtime']==data['runtime'].min()]

,imdb_id,budget,revenue,original_title,cast,director,tagline,overview,runtime,genres,production_companies,release_date,vote_average,release_year,profit
768,tt1449283,30000000,14460000,Winnie the Pooh,Jim Cummings|Travis Oates|Jim Cummings|Bud Luc...,Stephen Anderson|Don Hall,Oh Pooh.,"During an ordinary day in Hundred Acre Wood, W...",63,Animation|Family,Walt Disney Pictures|Walt Disney Animation Stu...,4/13/2011,6.8,2011,-15540000

In [105]:
answers['3']= 'Winnie the Pooh (tt1449283)'

# 4. Какова средняя длительность фильмов?

In [106]:
round(data['runtime'].mean())

110

In [107]:
answers['4']= '110'

# 5. Каково медианное значение длительности фильмов?

In [108]:
#достаточно обратиться снова к методу describe
data.describe()

,budget,revenue,runtime,vote_average,release_year,profit
count,1.889000e+03,1.889000e+03,1889.000000,1889.000000,1889.000000,1.889000e+03
mean,5.431083e+07,1.553653e+08,109.658549,6.140762,2007.860773,1.010545e+08
std,4.858721e+07,2.146698e+08,18.017041,0.764763,4.468841,1.830733e+08
min,5.000000e+06,2.033165e+06,63.000000,3.300000,2000.000000,-1.657101e+08
25%,2.000000e+07,3.456058e+07,97.000000,5.600000,2004.000000,5.000000e+06
50%,3.800000e+07,8.361541e+07,107.000000,6.100000,2008.000000,4.400041e+07
75%,7.200000e+07,1.782626e+08,120.000000,6.600000,2012.000000,1.201842e+08
max,3.800000e+08,2.781506e+09,214.000000,8.100000,2015.000000,2.544506e+09

In [109]:
answers['5']= '107'

# 6. Какой самый прибыльный фильм?
#### Внимание! Здесь и далее под «прибылью» или «убытками» понимается разность между сборами и бюджетом фильма. (прибыль = сборы - бюджет) в нашем датасете это будет (profit = revenue - budget)

In [110]:
#Столбец profit добавили ранее
data[data['profit']==data['profit'].max()]

,imdb_id,budget,revenue,original_title,cast,director,tagline,overview,runtime,genres,production_companies,release_date,vote_average,release_year,profit
239,tt0499549,237000000,2781505847,Avatar,Sam Worthington|Zoe Saldana|Sigourney Weaver|S...,James Cameron,Enter the World of Pandora.,"In the 22nd century, a paraplegic Marine is di...",162,Action|Adventure|Fantasy|Science Fiction,Ingenious Film Partners|Twentieth Century Fox ...,12/10/2009,7.1,2009,2544505847

In [111]:
answers['6']= 'Avatar (tt0499549)'

# 7. Какой фильм самый убыточный?

In [112]:
data[data['profit']==data['profit'].min()]

,imdb_id,budget,revenue,original_title,cast,director,tagline,overview,runtime,genres,production_companies,release_date,vote_average,release_year,profit
1245,tt1210819,255000000,89289910,The Lone Ranger,Johnny Depp|Armie Hammer|William Fichtner|Hele...,Gore Verbinski,Never Take Off the Mask,The Texas Rangers chase down a gang of outlaws...,149,Action|Adventure|Western,Walt Disney Pictures|Jerry Bruckheimer Films|I...,7/3/2013,6.0,2013,-165710090

In [113]:
answers['7']= 'The Lone Ranger (tt1210819)'

# 8. У скольких фильмов из датасета объем сборов оказался выше бюджета?

In [114]:
data[data['revenue']>data['budget']]['imdb_id'].count()

1478

In [115]:
answers['8']='1478'

# 9. Какой фильм оказался самым кассовым в 2008 году?

In [116]:
data2008[data2008['profit']==data2008['profit'].max()]

,imdb_id,budget,revenue,original_title,cast,director,tagline,overview,runtime,genres,production_companies,release_date,vote_average,release_year,profit
599,tt0468569,185000000,1001921825,The Dark Knight,Christian Bale|Michael Caine|Heath Ledger|Aaro...,Christopher Nolan,Why So Serious?,Batman raises the stakes in his war on crime. ...,152,Drama|Action|Crime|Thriller,DC Comics|Legendary Pictures|Warner Bros.|Syncopy,7/16/2008,8.1,2008,816921825

In [117]:
answers['9']= 'The Dark Knight (tt0468569)'

# 10. Самый убыточный фильм за период с 2012 по 2014 г. (включительно)?

In [118]:
data.query('profit==profit.min() & release_year in ["2012", "2013", "2014"]')

,imdb_id,budget,revenue,original_title,cast,director,tagline,overview,runtime,genres,production_companies,release_date,vote_average,release_year,profit
1245,tt1210819,255000000,89289910,The Lone Ranger,Johnny Depp|Armie Hammer|William Fichtner|Hele...,Gore Verbinski,Never Take Off the Mask,The Texas Rangers chase down a gang of outlaws...,149,Action|Adventure|Western,Walt Disney Pictures|Jerry Bruckheimer Films|I...,7/3/2013,6.0,2013,-165710090

In [119]:
answers['10']='The Lone Ranger (tt1210819)'

# 11. Какого жанра фильмов больше всего?

In [120]:
# эту задачу тоже можно решать разными подходами, попробуй реализовать разные варианты
# если будешь добавлять функцию - выноси ее в предобработку что в начале
Genres_count= splitter(data['genres'])
Genres_count.most_common()

[('Drama', 782),
 ('Comedy', 683),
 ('Thriller', 596),
 ('Action', 582),
 ('Adventure', 415),
 ('Crime', 315),
 ('Romance', 308),
 ('Family', 260),
 ('Science Fiction', 248),
 ('Fantasy', 222),
 ('Horror', 176),
 ('Mystery', 168),
 ('Animation', 139),
 ('Music', 64),
 ('History', 62),
 ('War', 58),
 ('Western', 19),
 ('Documentary', 8),
 ('Foreign', 2)]

In [121]:
answers['11']='Drama'

ВАРИАНТ 2

In [122]:
data_g=data.copy()
data_g['genres']=data.genres.str.split('|')
data_g2=data_g.explode('genres')
data_g2['genres'].value_counts()

Drama              782
Comedy             683
Thriller           596
Action             582
Adventure          415
Crime              315
Romance            308
Family             260
Science Fiction    248
Fantasy            222
Horror             176
Mystery            168
Animation          139
Music               64
History             62
War                 58
Western             19
Documentary          8
Foreign              2
Name: genres, dtype: int64

# 12. Фильмы какого жанра чаще всего становятся прибыльными?

In [123]:
revenue_genres = splitter(data[data['profit']>=0]['genres'])
revenue_genres.most_common()

[('Drama', 560),
 ('Comedy', 551),
 ('Thriller', 446),
 ('Action', 444),
 ('Adventure', 337),
 ('Romance', 242),
 ('Crime', 231),
 ('Family', 226),
 ('Science Fiction', 195),
 ('Fantasy', 188),
 ('Horror', 150),
 ('Animation', 120),
 ('Mystery', 119),
 ('Music', 47),
 ('History', 46),
 ('War', 41),
 ('Western', 12),
 ('Documentary', 7)]

In [124]:
answers['12']='Drama'

# 13. У какого режиссера самые большие суммарные кассовые сборы?

In [125]:
data.groupby(['director'])['revenue'].sum().sort_values(ascending=False)

director
Peter Jackson        6490593685
Christopher Nolan    4167548502
David Yates          4154295625
Michael Bay          3886938960
J.J. Abrams          3579169916
                        ...
David MichÃ´d           2295423
Steven Shainberg        2281089
Paul Schrader           2062066
Keanu Reeves            2054941
Simon Hunter            2033165
Name: revenue, Length: 957, dtype: int64

In [126]:
answers['13']='Peter Jackson'

### 2 вариант

In [127]:
data2=data.copy()
data2['director'] = data2.director.str.split('|')
data3=data2.explode('director')
data3.groupby(['director'])['revenue'].sum().sort_values(ascending=False)

director
Peter Jackson        6490593685
Christopher Nolan    4167548502
David Yates          4154295625
Michael Bay          3886938960
J.J. Abrams          3579169916
                        ...
David MichÃ´d           2295423
Steven Shainberg        2281089
Paul Schrader           2062066
Keanu Reeves            2054941
Simon Hunter            2033165
Name: revenue, Length: 997, dtype: int64

# 14. Какой режисер снял больше всего фильмов в стиле Action?

In [128]:
data_g=data.copy()
data_g['genres']=data.genres.str.split('|')
data_g['director']=data.director.str.split('|')
data_g1=data_g.explode('genres')
data_gd=data_g1.explode('director')
data_gd[data_gd['genres']=='Action'].groupby(['director'])['genres'].count().sort_values(ascending = False)

director
Robert Rodriguez      9
Paul W.S. Anderson    7
Michael Bay           7
Ridley Scott          6
Antoine Fuqua         6
                     ..
Joe Cornish           1
Roger Spottiswoode    1
Jimmy Hayward         1
Jim Gillespie         1
Jon Avnet             1
Name: genres, Length: 364, dtype: int64

In [129]:
answers['14']= 'Robert Rodriguez'

# 15. Фильмы с каким актером принесли самые высокие кассовые сборы в 2012 году?

In [130]:
data_a=data.copy()
data_a['cast']=data.cast.str.split('|')
data_a = data_a.explode('cast')
data_a[data_a['release_year']==2012].groupby(['cast']).sum()['revenue'].sort_values(ascending= False)

cast
Chris Hemsworth      2027450773
Denis Leary          1629460639
Anne Hathaway        1522851057
Chris Evans          1519557910
Robert Downey Jr.    1519557910
                        ...
Jason Bateman           3428048
Danny Huston            2106557
Sami Gayle              2106557
Josh Lucas              2106557
Nicolas Cage            2106557
Name: revenue, Length: 466, dtype: int64

In [131]:
answers['15']='Chris Hemsworth'

# 16. Какой актер снялся в большем количестве высокобюджетных фильмов?

In [132]:
data_budg = data[data['budget']>=data['budget'].mean()]
actor = splitter(data_budg['cast'])
actor.most_common()

[('Matt Damon', 18),
 ('Adam Sandler', 17),
 ('Angelina Jolie', 16),
 ('Tom Cruise', 15),
 ('Samuel L. Jackson', 15),
 ('Eddie Murphy', 15),
 ('Mark Wahlberg', 14),
 ('Hugh Jackman', 14),
 ('Ben Stiller', 14),
 ('Jamie Foxx', 14),
 ('Russell Crowe', 14),
 ('Johnny Depp', 13),
 ('Jude Law', 13),
 ('Bruce Willis', 13),
 ('Will Smith', 13),
 ('Dwayne Johnson', 12),
 ('Ian McKellen', 12),
 ('Brad Pitt', 12),
 ('Owen Wilson', 12),
 ('Cameron Diaz', 12),
 ('Nicolas Cage', 12),
 ('Robert De Niro', 12),
 ('Leonardo DiCaprio', 11),
 ('Daniel Craig', 11),
 ('Robert Downey Jr.', 11),
 ('Steve Buscemi', 11),
 ('Vin Diesel', 10),
 ('Mark Ruffalo', 10),
 ('Jack Black', 10),
 ('Denzel Washington', 10),
 ('Emma Watson', 10),
 ('Gary Oldman', 10),
 ('Tom Hanks', 10),
 ('Orlando Bloom', 10),
 ('Ralph Fiennes', 9),
 ('Cate Blanchett', 9),
 ('Michael Caine', 9),
 ('Ewan McGregor', 9),
 ('Paul Bettany', 9),
 ('Brendan Gleeson', 9),
 ('Shia LaBeouf', 9),
 ('Nicole Kidman', 9),
 ('Colin Farrell', 9),
 ('Rachel Weisz', 9),
 ('Halle Berry', 9),
 ('Charlize Theron', 8),
 ('Kevin James', 8),
 ('Chris Hemsworth', 8),
 ('Helena Bonham Carter', 8),
 ('Josh Hutcherson', 8),
 ('George Clooney', 8),
 ('James Franco', 8),
 ('Christian Bale', 8),
 ('Gerard Butler', 8),
 ('Sylvester Stallone', 8),
 ('Rosario Dawson', 8),
 ('Ben Kingsley', 8),
 ('Bill Nighy', 8),
 ('Daniel Radcliffe', 8),
 ('Rupert Grint', 8),
 ('Jim Carrey', 8),
 ('Vince Vaughn', 8),
 ('Alec Baldwin', 8),
 ('Steve Carell', 8),
 ('Harrison Ford', 7),
 ('Jason Statham', 7),
 ('Chris Evans', 7),
 ('Woody Harrelson', 7),
 ('Josh Brolin', 7),
 ('Jeff Bridges', 7),
 ('Anne Hathaway', 7),
 ('Patrick Stewart', 7),
 ('Jennifer Connelly', 7),
 ('Anthony Hopkins', 7),
 ('Morgan Freeman', 7),
 ('Billy Crudup', 7),
 ('Jason Lee', 7),
 ('Jessica Biel', 7),
 ('Julia Roberts', 7),
 ('Ryan Reynolds', 7),
 ('Liam Neeson', 7),
 ('Karl Urban', 7),
 ('Richard Jenkins', 7),
 ('Chris Rock', 7),
 ('Kate Winslet', 6),
 ('Paul Walker', 6),
 ('Arnold Schwarzenegger', 6),
 ('Sean Bean', 6),
 ('Scarlett Johansson', 6),
 ('Elizabeth Banks', 6),
 ('Ving Rhames', 6),
 ('Mark Strong', 6),
 ('Jeffrey Wright', 6),
 ('Gwyneth Paltrow', 6),
 ('Matthew McConaughey', 6),
 ('Rosamund Pike', 6),
 ('Logan Lerman', 6),
 ('Robin Williams', 6),
 ('Stanley Tucci', 6),
 ('Mel Gibson', 6),
 ('Kevin Costner', 6),
 ('John Goodman', 6),
 ('Aaron Eckhart', 6),
 ('Justin Long', 6),
 ('Will Ferrell', 6),
 ('Seann William Scott', 6),
 ('Paul Giamatti', 6),
 ('Dustin Hoffman', 6),
 ('Mike Myers', 6),
 ('Eva Mendes', 6),
 ('Kate Beckinsale', 6),
 ('Jon Voight', 6),
 ('Jackie Chan', 6),
 ('Tobey Maguire', 6),
 ('Keanu Reeves', 6),
 ('Guy Pearce', 6),
 ('John Leguizamo', 6),
 ('Tommy Lee Jones', 6),
 ('Michelle Rodriguez', 5),
 ('Michael PeÃ±a', 5),
 ('Paul Rudd', 5),
 ('Jennifer Lawrence', 5),
 ('Carla Gugino', 5),
 ('Ioan Gruffudd', 5),
 ('Simon Pegg', 5),
 ('Giovanni Ribisi', 5),
 ('Frances McDormand', 5),
 ('Elijah Wood', 5),
 ('Jake Gyllenhaal', 5),
 ('Sam Worthington', 5),
 ('Delroy Lindo', 5),
 ('Bradley Cooper', 5),
 ('Donald Sutherland', 5),
 ('Ben Affleck', 5),
 ('Andy Serkis', 5),
 ('John Turturro', 5),
 ('Jonah Hill', 5),
 ('Julianne Moore', 5),
 ('John Malkovich', 5),
 ('Ian McShane', 5),
 ('Chris Pine', 5),
 ('Keira Knightley', 5),
 ('Jessica Alba', 5),
 ('Eric Bana', 5),
 ('Benjamin Bratt', 5),
 ('Hank Azaria', 5),
 ('John Travolta', 5),
 ('David Cross', 5),
 ('Clive Owen', 5),
 ('Sam Elliott', 5),
 ('Don Cheadle', 5),
 ('Ron Perlman', 5),
 ('Antonio Banderas', 5),
 ('Peter Sarsgaard', 5),
 ('Zach Galifianakis', 5),
 ('Nick Nolte', 5),
 ('Brendan Fraser', 5),
 ('Jennifer Aniston', 5),
 ('Edward Norton', 5),
 ('Judi Dench', 5),
 ('John C. Reilly', 5),
 ('Sacha Baron Cohen', 5),
 ('Kirsten Dunst', 5),
 ('Djimon Hounsou', 5),
 ('Catherine Zeta-Jones', 5),
 ('Tom Hardy', 4),
 ('Kristen Wiig', 4),
 ('Christoph Waltz', 4),
 ('Michelle Monaghan', 4),
 ('Liam Hemsworth', 4),
 ('Amanda Seyfried', 4),
 ('Steve Martin', 4),
 ('Ray Winstone', 4),
 ('Rose Byrne', 4),
 ('Tom Hiddleston', 4),
 ('Michael Fassbender', 4),
 ('Megan Fox', 4),
 ('Will Arnett', 4),
 ('William Fichtner', 4),
 ('Marton Csokas', 4),
 ('Emma Stone', 4),
 ('Bill Paxton', 4),
 ('Joel Edgerton', 4),
 ('Bryan Cranston', 4),
 ('Jay Baruchel', 4),
 ('Eva Green', 4),
 ('David Wenham', 4),
 ('Michael Gambon', 4),
 ('Mickey Rourke', 4),
 ('Joseph Gordon-Levitt', 4),
 ('Bill Murray', 4),
 ('Carrie-Anne Moss', 4),
 ('Bruce Greenwood', 4),
 ('Patrick Wilson', 4),
 ('Chiwetel Ejiofor', 4),
 ('Thandie Newton', 4),
 ('Anna Faris', 4),
 ('Amy Adams', 4),
 ('Susan Sarandon', 4),
 ('PenÃ©lope Cruz', 4),
 ('Jon Favreau', 4),
 ('Luis GuzmÃ¡n', 4),
 ('Jason Bateman', 4),
 ('Seth Rogen', 4),
 ('Reese Witherspoon', 4),
 ('Tyrese Gibson', 4),
 ('Catherine Keener', 4),
 ('James Cromwell', 4),
 ('Julie Andrews', 4),
 ('Alfred Molina', 4),
 ('Salma Hayek', 4),
 ('Kristen Stewart', 4),
 ('Peter Facinelli', 4),
 ('Jason Isaacs', 4),
 ('Ashton Kutcher', 4),
 ('Jack Nicholson', 4),
 ('Viggo Mortensen', 4),
 ('Liv Tyler', 4),
 ('Ed Harris', 4),
 ('Heath Ledger', 4),
 ('Kurt Russell', 4),
 ('Angela Bassett', 4),
 ('TÃ©a Leoni', 4),
 ('Terrence Howard', 4),
 ('Hayden Christensen', 4),
 ('Terence Stamp', 4),
 ('Anthony Mackie', 4),
 ('Zooey Deschanel', 4),
 ('Matthew Broderick', 4),
 ('Ed Helms', 4),
 ('Hugo Weaving', 4),
 ('Geoffrey Rush', 4),
 ('Natalie Portman', 4),
 ('Denis Leary', 4),
 ('Brian Cox', 4),
 ('Willem Dafoe', 4),
 ('Joaquin Phoenix', 4),
 ('Famke Janssen', 4),
 ('Peter Stormare', 4),
 ('Kerry Washington', 4),
 ('Billy Connolly', 4),
 ('Drew Barrymore', 4),
 ('RenÃ©e Zellweger', 4),
 ('Christopher Walken', 4),
 ('Bryce Dallas Howard', 3),
 ('Theo James', 3),
 ('Miles Teller', 3),
 ('Jason Clarke', 3),
 ('Jai Courtney', 3),
 ('Jessica Chastain', 3),
 ('Sandra Bullock', 3),
 ('Michael Keaton', 3),
 ('Bill Hader', 3),
 ('Monica Bellucci', 3),
 ('Mila Kunis', 3),
 ('Channing Tatum', 3),
 ('Josh Gad', 3),
 ('Michael Douglas', 3),
 ('Bobby Cannavale', 3),
 ('Hugh Laurie', 3),
 ('Alexandra Daddario', 3),
 ('Jeremy Renner', 3),
 ('Amy Ryan', 3),
 ('Henry Cavill', 3),
 ('Armie Hammer', 3),
 ('Kate Mara', 3),
 ('Jamie Bell', 3),
 ('Toby Kebbell', 3),
 ('Garrett Hedlund', 3),
 ('Andy Samberg', 3),
 ('Rachel McAdams', 3),
 ('Marion Cotillard', 3),
 ('Charlie Hunnam', 3),
 ('Casey Affleck', 3),
 ('Zoe Saldana', 3),
 ('Robert Redford', 3),
 ('Martin Freeman', 3),
 ('Richard Armitage', 3),
 ('Neil Patrick Harris', 3),
 ('James McAvoy', 3),
 ('Li Bingbing', 3),
 ('Colm Feore', 3),
 ('Sienna Miller', 3),
 ('Ken Watanabe', 3),
 ('Elle Fanning', 3),
 ('Sharlto Copley', 3),
 ('Luke Evans', 3),
 ('Dominic Cooper', 3),
 ('John Hurt', 3),
 ('Rufus Sewell', 3),
 ('Abbie Cornish', 3),
 ('Jesse Eisenberg', 3),
 ('Leslie Mann', 3),
 ('Andy GarcÃ\xada', 3),
 ('Emily Browning', 3),
 ('Miranda Otto', 3),
 ('William Hurt', 3),
 ('Stephen Lang', 3),
 ('Christopher Plummer', 3),
 ('Malin Ã…kerman', 3),
 ('Amanda Peet', 3),
 ('Stellan SkarsgÃ¥rd', 3),
 ('Dennis Quaid', 3),
 ('Dakota Fanning', 3),
 ('Kristen Bell', 3),
 ('Kiefer Sutherland', 3),
 ('Robin Wright', 3),
 ('Josh Duhamel', 3),
 ('Meryl Streep', 3),
 ('Olivia Wilde', 3),
 ('Freddie Highmore', 3),
 ('Jordana Brewster', 3),
 ('Radha Mitchell', 3),
 ('Liev Schreiber', 3),
 ('Hugh Grant', 3),
 ('Sarah Jessica Parker', 3),
 ('Mary Steenburgen', 3),
 ('Russell Brand', 3),
 ('Emily Mortimer', 3),
 ('Skandar Keynes', 3),
 ('Georgie Henley', 3),
 ('Jason Flemyng', 3),
 ('Mary Elizabeth Winstead', 3),
 ('Brandon T. Jackson', 3),
 ('Mary-Louise Parker', 3),
 ('Maria Bello', 3),
 ('Robert Pattinson', 3),
 ('Taylor Lautner', 3),
 ('Greg Kinnear', 3),
 ('Kristin Davis', 3),
 ('Chris Noth', 3),
 ('James Marsden', 3),
 ('Dan Aykroyd', 3),
 ('Milla Jovovich', 3),
 ('Cuba Gooding Jr.', 3),
 ('Michael Clarke Duncan', 3),
 ('James Gandolfini', 3),
 ('Laurence Fishburne', 3),
 ('Billy Bob Thornton', 3),
 ('Teri Polo', 3),
 ('Lucy Liu', 3),
 ('Jada Pinkett Smith', 3),
 ('David Schwimmer', 3),
 ('Jeffrey Tambor', 3),
 ('Thomas Kretschmann', 3),
 ('Kenneth Branagh', 3),
 ('Cliff Curtis', 3),
 ('Michael Chiklis', 3),
 ('Jaden Smith', 3),
 ('Sienna Guillory', 3),
 ('Al Pacino', 3),
 ('Spencer Breslin', 3),
 ('Paula Patton', 3),
 ('Tim Robbins', 3),
 ('Justin Bartha', 3),
 ('Ken Jeong', 3),
 ('Jane Lynch', 3),
 ('Isla Fisher', 3),
 ('CiarÃ¡n Hinds', 3),
 ('Lily Collins', 3),
 ('Kevin Bacon', 3),
 ('Ray Romano', 3),
 ('Chris Cooper', 3),
 ('Emma Thompson', 3),
 ('William Shatner', 3),
 ('Cole Hauser', 3),
 ('Randy Quaid', 3),
 ('Harvey Keitel', 3),
 ('Scott Glenn', 3),
 ('David Oyelowo', 3),
 ('Michelle Pfeiffer', 3),
 ('David Spade', 3),
 ('Marisa Tomei', 3),
 ('Josh Lucas', 3),
 ('David Thewlis', 3),
 ('Connie Nielsen', 3),
 ('Bruce McGill', 3),
 ('Shirley MacLaine', 3),
 ('Hiroyuki Sanada', 3),
 ('Sean Penn', 3),
 ('Richard Roxburgh', 3),
 ('Val Kilmer', 3),
 ('Emmy Rossum', 3),
 ('Miranda Richardson', 3),
 ('Chris Pratt', 2),
 ('Irrfan Khan', 2),
 ('Nicholas Hoult', 2),
 ('Shailene Woodley', 2),
 ('Domhnall Gleeson', 2),
 ('J.K. Simmons', 2),
 ('Jeff Daniels', 2),
 ('Allison Janney', 2),
 ('Steve Coogan', 2),
 ('Amy Poehler', 2),
 ('LÃ©a Seydoux', 2),
 ('Evangeline Lilly', 2),
 ('Corey Stoll', 2),
 ('Colin Firth', 2),
 ('Giancarlo Esposito', 2),
 ('Alicia Vikander', 2),
 ('Elizabeth Debicki', 2),
 ('Rihanna', 2),
 ('Jennifer Lopez', 2),
 ('Edgar RamÃ\xadrez', 2),
 ('Teresa Palmer', 2),
 ('Viola Davis', 2),
 ('Benjamin Walker', 2),
 ('Ben Whishaw', 2),
 ('Rooney Mara', 2),
 ('Selena Gomez', 2),
 ('Mia Wasikowska', 2),
 ('Sebastian Stan', 2),
 ('Ken Stott', 2),
 ('Graham McTavish', 2),
 ('Jamie Chung', 2),
 ('Rami Malek', 2),
 ('Ray Stevenson', 2),
 ('Nicola Peltz', 2),
 ('Keri Russell', 2),
 ('ChloÃ« Grace Moretz', 2),
 ('Andrew Garfield', 2),
 ('Emily Blunt', 2),
 ('Aaron Paul', 2),
 ('Ben Barnes', 2),
 ('Kit Harington', 2),
 ('Lena Headey', 2),
 ('Joel Kinnaman', 2),
 ('Jackie Earle Haley', 2),
 ('Adewale Akinnuoye-Agbaje', 2),
 ('RamÃ³n RodrÃ\xadguez', 2),
 ('Yvonne Strahovski', 2),
 ('Kellan Lutz', 2),
 ('Sigourney Weaver', 2),
 ('MÃ©lanie Laurent', 2),
 ('Julie Walters', 2),
 ('Zachary Quinto', 2),
 ('Anton Yelchin', 2),
 ('Eddie Marsan', 2),
 ('Jeffrey Dean Morgan', 2),
 ('John Cusack', 2),
 ('Oliver Platt', 2),
 ('Keith David', 2),
 ('Marlon Wayans', 2),
 ('James Caan', 2),
 ('Saoirse Ronan', 2),
 ('Sam Rockwell', 2),
 ('Tracy Morgan', 2),
 ('Zachary Levi', 2),
 ('Mary Kay Place', 2),
 ('Michael Cera', 2),
 ('Oscar Isaac', 2),
 ('Danny Huston', 2),
 ('Lynn Collins', 2),
 ('Jason Segel', 2),
 ('Dolph Lundgren', 2),
 ('Michelle Williams', 2),
 ('Mandy Moore', 2),
 ('Tim Allen', 2),
 ('Ned Beatty', 2),
 ('Joan Cusack', 2),
 ('Timothy Dalton', 2),
 ('Gemma Arterton', 2),
 ('Anna Kendrick', 2),
 ('Barbra Streisand', 2),
 ('Helen Mirren', 2),
 ('Tina Fey', 2),
 ('Ashley Greene', 2),
 ('Jordi MollÃ\xa0', 2),
 ('Javier Bardem', 2),
 ('Katherine Heigl', 2),
 ('Tom Selleck', 2),
 ('Cynthia Nixon', 2),
 ('Kim Cattrall', 2),
 ('Essie Davis', 2),
 ('Eric Dane', 2),
 ('Cam Gigandet', 2),
 ('Julianne Hough', 2),
 ('Stephanie Szostak', 2),
 ('Bette Midler', 2),
 ('Carey Mulligan', 2),
 ('Justin Timberlake', 2),
 ('John Cleese', 2),
 ('Billy Crystal', 2),
 ("Frances O'Connor", 2),
 ('John Lithgow', 2),
 ('Josh Hartnett', 2),
 ('John Hannah', 2),
 ('Arnold Vosloo', 2),
 ('Michael J. Fox', 2),
 ('James Garner', 2),
 ('Noah Taylor', 2),
 ('Tim Roth', 2),
 ('Kris Kristofferson', 2),
 ('Tom Sizemore', 2),
 ('Chris Tucker', 2),
 ('Zhang Ziyi', 2),
 ('Ernie Reyes, Jr.', 2),
 ('Elizabeth Perkins', 2),
 ('Sam Shepard', 2),
 ('Dylan Baker', 2),
 ('Gene Hackman', 2),
 ('Dominic West', 2),
 ('Edward Burns', 2),
 ('Martin Landau', 2),
 ('David Ogden Stiers', 2),
 ('Courteney Cox', 2),
 ('David Hyde Pierce', 2),
 ('Til Schweiger', 2),
 ('David Andrews', 2),
 ('William H. Macy', 2),
 ('Jeff Garlin', 2),
 ('Olga Kurylenko', 2),
 ('Jet Li', 2),
 ('Selma Blair', 2),
 ('Michael Rooker', 2),
 ('William Moseley', 2),
 ('Anna Popplewell', 2),
 ('Kathy Bates', 2),
 ('Michael Ealy', 2),
 ('Malcolm McDowell', 2),
 ('Alan Arkin', 2),
 ('Ali Suliman', 2),
 ('Adam Scott', 2),
 ('Kate Hudson', 2),
 ('Ewen Bremner', 2),
 ('Lambert Wilson', 2),
 ('Charlotte Rampling', 2),
 ('Robert Duvall', 2),
 ('Christina Ricci', 2),
 ('Matthew Fox', 2),
 ('Gabriel Macht', 2),
 ('Paz Vega', 2),
 ('Kevin Kline', 2),
 ('Gabrielle Union', 2),
 ('Goran Visnjic', 2),
 ('Bailee Madison', 2),
 ('Noomi Rapace', 2),
 ('Larry the Cable Guy', 2),
 ('Eddie Izzard', 2),
 ('Vanessa Hudgens', 2),
 ('Emily Watson', 2),
 ('Asa Butterfield', 2),
 ('Dominic Purcell', 2),
 ('Maggie Q', 2),
 ('Isabel Lucas', 2),
 ('Katie Holmes', 2),
 ('Amy Sedaris', 2),
 ('Jason Momoa', 2),
 ('Lea Michele', 2),
 ('Johnny A. Sanchez', 2),
 ('Seth Green', 2),
 ('Queen Latifah', 2),
 ('Richard Harris', 2),
 ('Franka Potente', 2),
 ('Ian McDiarmid', 2),
 ('Max von Sydow', 2),
 ('Abigail Breslin', 2),
 ('Elias Koteas', 2),
 ('Liam Aiken', 2),
 ('Paul Newman', 2),
 ('BeyoncÃ© Knowles', 2),
 ('Mark Addy', 2),
 ('Adam Beach', 2),
 ('Izabella Scorupco', 2),
 ('Naomie Harris', 2),
 ('Idris Elba', 2),
 ('Martin Sheen', 2),
 ('Kevin McKidd', 2),
 ('Jim Broadbent', 2),
 ('Jim Sturgess', 2),
 ('Jonny Lee Miller', 2),
 ('Timothy Spall', 2),
 ('Taylor Kitsch', 2),
 ('Tadanobu Asano', 2),
 ('Nathan Lane', 2),
 ('Jack Davenport', 2),
 ('Claire Danes', 2),
 ('Jennifer Garner', 2),
 ('Martin Lawrence', 2),
 ('TchÃ©ky Karyo', 2),
 ('Bernie Mac', 2),
 ('Robert Patrick', 2),
 ('Steve Zahn', 2),
 ('Timothy Olyphant', 2),
 ('Diane Lane', 2),
 ('Jodie Foster', 2),
 ('Alice Braga', 2),
 ('Diego Luna', 2),
 ('James Badge Dale', 2),
 ('Patton Oswalt', 2),
 ('Cloris Leachman', 2),
 ('Max Martini', 2),
 ('Maggie Gyllenhaal', 2),
 ('Sung Kang', 2),
 ('Sophie Okonedo', 2),
 ('Zach Braff', 2),
 ('Jim Belushi', 2),
 ('AnnaSophia Robb', 2),
 ('Julian McMahon', 2),
 ('Lauren Graham', 2),
 ('Gong Li', 2),
 ('Amber Valletta', 2),
 ('Jeremy Irons', 2),
 ('Adrien Brody', 2),
 ('Lucas Black', 2),
 ('Donal Logue', 2),
 ('Paddy Considine', 2),
 ('Bonnie Hunt', 2),
 ('Yvan Attal', 2),
 ('Mads Mikkelsen', 2),
 ('Jean Reno', 2),
 ('Philip Seymour Hoffman', 2),
 ('Jonathan Rhys Meyers', 2),
 ('David Strathairn', 2),
 ('Sharon Stone', 2),
 ('Jacinda Barrett', 2),
 ('Gary Sinise', 2),
 ('Danny Glover', 2),
 ('Julia Stiles', 2),
 ('Diane Kruger', 2),
 ('Chi McBride', 2),
 ('Jane Krakowski', 2),
 ('Glenn Close', 2),
 ('Patrick Warburton', 2),
 ('John Michael Higgins', 2),
 ('Helen Hunt', 2),
 ("Vincent D'Onofrio", 1),
 ('Nick Robinson', 1),
 ('Hugh Keays-Byrne', 1),
 ('Josh Helman', 1),
 ('Ansel Elgort', 1),
 ('Mark Hamill', 1),
 ('Carrie Fisher', 1),
 ('Adam Driver', 1),
 ('Daisy Ridley', 1),
 ('Will Poulter', 1),
 ('Paul Anderson', 1),
 ('Emilia Clarke', 1),
 ('Jon Hamm', 1),
 ('Phyllis Smith', 1),
 ('Richard Kind', 1),
 ('Lewis Black', 1),
 ('Eddie Redmayne', 1),
 ('Douglas Booth', 1),
 ('Peter Dinklage', 1),
 ('Lily James', 1),
 ('Richard Madden', 1),
 ('Holliday Grainger', 1),
 ('Britt Robertson', 1),
 ('Raffey Cassidy', 1),
 ('Thomas Robinson', 1),
 ('Archie Panjabi', 1),
 ('Rebecca Ferguson', 1),
 ('Seth MacFarlane', 1),
 ('Jessica Barth', 1),
 ('Taron Egerton', 1),
 ("Dylan O'Brien", 1),
 ('Kaya Scodelario', 1),
 ('Thomas Brodie-Sangster', 1),
 ('Aidan Gillen', 1),
 ('Dylan Minnette', 1),
 ('Odeya Rush', 1),
 ('Jillian Bell', 1),
 ('Raymond Ochoa', 1),
 ('Jack Bright', 1),
 ('Maleah Nipay-Padilla', 1),
 ('Rose Leslie', 1),
 ('Ã“lafur Darri Ã“lafsson', 1),
 ('Luca Calvani', 1),
 ('Jim Parsons', 1),
 ('Matt Jones', 1),
 ('John Hawkes', 1),
 ('Luke Bracey', 1),
 ('Olivia Munn', 1),
 ('Leehom Wang', 1),
 ('Tang Wei', 1),
 ('Holt McCallany', 1),
 ('Michael B. Jordan', 1),
 ('Melissa McCarthy', 1),
 ('Miranda Hart', 1),
 ('Cillian Murphy', 1),
 ('Levi Miller', 1),
 ('Noah Schnapp', 1),
 ('Bill Melendez', 1),
 ('Venus Schultheis', 1),
 ('Hadley Belle Miller', 1),
 ('Madisyn Shipman', 1),
 ('Jim Beaver', 1),
 ('Tom Kenny', 1),
 ('Bill Fagerbakke', 1),
 ('Rodger Bumpass', 1),
 ('Clancy Brown', 1),
 ('Carolyn Lawrence', 1),
 ('Dave Bautista', 1),
 ('Scott Adsit', 1),
 ('Ryan Potter', 1),
 ('Daniel Henney', 1),
 ('T.J. Miller', 1),
 ('Carrie Coon', 1),
 ('Tyler Perry', 1),
 ('Jon Bernthal', 1),
 ('Rebel Wilson', 1),
 ('Alan Ritchson', 1),
 ('Noel Fisher', 1),
 ('Jack Reynor', 1),
 ('Judy Greer', 1),
 ('David Harbour', 1),
 ('Haley Bennett', 1),
 ('Dane DeHaan', 1),
 ('Jonas Armstrong', 1),
 ('Kyle Gallner', 1),
 ('Cole Konis', 1),
 ('Ben Reed', 1),
 ('Ben Mendelsohn', 1),
 ('Aaron Taylor-Johnson', 1),
 ('Elizabeth Olsen', 1),
 ('Juliette Binoche', 1),
 ('Juno Temple', 1),
 ('Isobelle Molloy', 1),
 ('Craig Berry', 1),
 ('Alison Brie', 1),
 ('David Burrows', 1),
 ('Sarah Gadon', 1),
 ('Art Parkinson', 1),
 ('Charles Dance', 1),
 ('Tom McGrath', 1),
 ('Chris Miller', 1),
 ('Christopher Knights', 1),
 ('Conrad Vernon', 1),
 ('Sullivan Stapleton', 1),
 ('Callan Mulvey', 1),
 ('Peter Capaldi', 1),
 ('Imelda Staunton', 1),
 ('Aksel Hennie', 1),
 ('Nonso Anozie', 1),
 ('Gemma Chan', 1),
 ('Rebecca Hall', 1),
 ('Ty Burrell', 1),
 ('Max Charles', 1),
 ('Ariel Winter', 1),
 ('Ellie Kemper', 1),
 ("Jack O'Connell", 1),
 ('Takamasa Ishihara', 1),
 ('Finn Wittrock', 1),
 ('Jessica Lucas', 1),
 ('QuvenzhanÃ© Wallis', 1),
 ('Imogen Poots', 1),
 ('Isaac Hempstead Wright', 1),
 ('Dee Bradley Baker', 1),
 ('Steve Blum', 1),
 ('Jessica Brown Findlay', 1),
 ('Liam McIntyre', 1),
 ('Gaia Weiss', 1),
 ('Scott Adkins', 1),
 ('Roxanne McKee', 1),
 ('Eli Roth', 1),
 ('Tom Felton', 1),
 ('Ed Asner', 1),
 ('Jordan Nagai', 1),
 ('Bob Peterson', 1),
 ('Leonard Nimoy', 1),
 ('Moon Bloodgood', 1),
 ('Ayelet Zurer', 1),
 ('Pierfrancesco Favino', 1),
 ('Anika Noni Rose', 1),
 ('Bruno Campos', 1),
 ('Michael-Leon Wooley', 1),
 ('Jennifer Cody', 1),
 ('Mr. T', 1),
 ('Teri Hatcher', 1),
 ('Jennifer Saunders', 1),
 ('Dawn French', 1),
 ('Steve Valentine', 1),
 ('Daryl Sabara', 1),
 ('Sage Ryan', 1),
 ('Victor Gojcaj', 1),
 ('Matthew Gray Gubler', 1),
 ('Rainn Wilson', 1),
 ('Lake Bell', 1),
 ('Anna Friel', 1),
 ('Danny McBride', 1),
 ('Jorma Taccone', 1),
 ('Matt Lauer', 1),
 ('Tony Kgoroge', 1),
 ('Patrick Mofokeng', 1),
 ('Matt Stern', 1),
 ('Max Minghella', 1),
 ('Ashraf Barhom', 1),
 ('Michael Lonsdale', 1),
 ('John Ortiz', 1),
 ('Tom Wilkinson', 1),
 ('Lisa Roberts Gillan', 1),
 ('Nelsan Ellis', 1),
 ('Michael Bunin', 1),
 ('Natalia Klimas', 1),
 ('Ellen Page', 1),
 ('Crispin Glover', 1),
 ('Eric Roberts', 1),
 ('Randy Couture', 1),
 ('Craig Ferguson', 1),
 ('America Ferrera', 1),
 ('Bruce Boxleitner', 1),
 ('Yaya DaCosta', 1),
 ('Donna Murphy', 1),
 ('M.C. Gainey', 1),
 ('Daniel Olbrychski', 1),
 ('Gary Sweet', 1),
 ('Arthur Angel', 1),
 ('Steven Berkoff', 1),
 ('Steve Toussaint', 1),
 ('Kieran Culkin', 1),
 ('Jake Abel', 1),
 ('Ethan Suplee', 1),
 ('Kevin Corrigan', 1),
 ('Maya Rudolph', 1),
 ('Jennifer Beals', 1),
 ('Taraji P. Henson', 1),
 ('Jimmi Simpson', 1),
 ('Noah Ringer', 1),
 ('Jackson Rathbone', 1),
 ('Dev Patel', 1),
 ('Shaun Toub', 1),
 ("Chris O'Dowd", 1),
 ('Juliette Lewis', 1),
 ("Catherine O'Hara", 1),
 ('Alex Borstein', 1),
 ('Emily Barclay', 1),
 ('Deborra-Lee Furness', 1),
 ('Cher', 1),
 ('Christina Aguilera', 1),
 ('Jemaine Clement', 1),
 ('Christina Applegate', 1),
 ('Pascale Hutton', 1),
 ('Kathryn Hahn', 1),
 ('Frank Langella', 1),
 ('Tom Cavanagh', 1),
 ('Christine Taylor', 1),
 ('Shawn Roberts', 1),
 ("Denis O'Hare", 1),
 ('Wentworth Miller', 1),
 ('Ali Larter', 1),
 ('Kim Coates', 1),
 ('Kacey Barnfield', 1),
 ('Robbie Coltrane', 1),
 ('Mary Gibbs', 1),
 ('James Coburn', 1),
 ('Haley Joel Osment', 1),
 ('Sam Robards', 1),
 ('Jake Thomas', 1),
 ('Vincent Cassel', 1),
 ('Oded Fehr', 1),
 ('Corey Burton', 1),
 ('Claudia Christian', 1),
 ('John Mahoney', 1),
 ('Iain Glen', 1),
 ('Joseph Fiennes', 1),
 ('Bob Hoskins', 1),
 ('Shannyn Sossamon', 1),
 ('Laura Fraser', 1),
 ('Roselyn SÃ¡nchez', 1),
 ('Jeff Goldblum', 1),
 ('Alexander Pollock', 1),
 ('Miriam Margolyes', 1),
 ('Catherine McCormack', 1),
 ('Stephen Dillane', 1),

In [133]:
answers['16']='Matt Damon'

# 17. В фильмах какого жанра больше всего снимался Nicolas Cage?

In [134]:
data_Ni = data_a[data_a['cast']=='Nicolas Cage'].copy()
data_Ni['genres'] = data_Ni.genres.str.split('|')
data_NiCa= data_Ni.explode('genres')
data_NiCa.groupby(['genres']).count()['imdb_id'].sort_values(ascending= False)

genres
Action             17
Thriller           15
Drama              12
Crime              10
Fantasy             8
Adventure           7
Comedy              6
Science Fiction     4
Mystery             3
Family              3
Animation           3
History             2
War                 1
Romance             1
Horror              1
Name: imdb_id, dtype: int64

In [135]:
answers['17']='Action'

# 18. Самый убыточный фильм от Paramount Pictures

In [136]:
data_s=data.copy()
data_s['production_companies']=data_s.production_companies.str.split('|')
data_st=data_s.explode('production_companies')
data_stPar=data_st[data_st['production_companies']=='Paramount Pictures'].copy()
data_stPar[data_stPar['profit']==data_stPar['profit'].min()]

,imdb_id,budget,revenue,original_title,cast,director,tagline,overview,runtime,genres,production_companies,release_date,vote_average,release_year,profit
925,tt0267626,100000000,35168966,K-19: The Widowmaker,Harrison Ford|Liam Neeson|Peter Sarsgaard|Joss...,Kathryn Bigelow,Fate has found its hero.,When Russia's first nuclear submarine malfunct...,138,Thriller|Drama|History,Paramount Pictures,7/19/2002,6.0,2002,-64831034

In [137]:
answers['18']='K-19: The Widowmaker (tt0267626)'

# 19. Какой год стал самым успешным по суммарным кассовым сборам?

In [138]:
data.groupby(['release_year']).sum()['profit'].sort_values(ascending=False)

release_year
2015    18668572378
2014    16397812953
2012    16077001687
2013    15243179791
2011    14730241341
2010    13531204961
2009    13423744372
2008    11663881990
2007    11565911801
2004     9634180720
2003     9228823312
2002     9002361487
2005     8981925558
2006     8691077320
2001     7950614865
2000     6101399805
Name: profit, dtype: int64

In [139]:
answers['19']='2015'

# 20. Какой самый прибыльный год для студии Warner Bros?

In [140]:
data_st[data_st.production_companies.str.contains('Warner Bros', na= False)].groupby(['release_year'])[
    'profit'].sum().sort_values(ascending = False)

release_year
2014    2292949646
2007    2201675217
2008    2134595031
2010    1974712985
2011    1871393682
2003    1844008221
2009    1822454136
2013    1636453400
2004    1631933725
2005    1551980298
2001    1282142579
2012    1258020056
2002    1022709901
2015     870368348
2006     625351872
2000     452631386
Name: profit, dtype: int64

In [141]:
answers['20']='2014'

# 21. В каком месяце за все годы суммарно вышло больше всего фильмов?

In [142]:
data21=data.copy()
data21.release_date= pd.to_datetime(data.release_date)
data21['release_date']=data21.release_date.apply(lambda x:
                                                 x.strftime('%m'))
data21.groupby('release_date')['original_title'].count().sort_values(ascending = False)

release_date
09    227
12    190
10    186
08    161
03    156
04    149
06    147
11    146
07    142
05    140
02    135
01    110
Name: original_title, dtype: int64

In [143]:
answers['21']='Сентябрь'

# 22. Сколько суммарно вышло фильмов летом? (за июнь, июль, август)

In [144]:
data22=data.copy()
data22.release_date= pd.to_datetime(data.release_date)
data22[data22.release_date.dt.month.isin([6,7,8])].count()

imdb_id                 450
budget                  450
revenue                 450
original_title          450
cast                    450
director                450
tagline                 450
overview                450
runtime                 450
genres                  450
production_companies    450
release_date            450
vote_average            450
release_year            450
profit                  450
dtype: int64

In [145]:
answers['22']='450'

# 23. Для какого режиссера зима – самое продуктивное время года?

In [146]:
data23=data.copy()
data23.release_date= pd.to_datetime(data.release_date)
data23['director']=data23.director.str.split('|')
data23d=data23.explode('director')
data23d[data23d.release_date.dt.month.isin([1,2,12])].groupby('director')['imdb_id'].count().sort_values(ascending=False)

director
Peter Jackson            7
Steven Soderbergh        6
Clint Eastwood           6
Martin Scorsese          4
Adam Shankman            4
                        ..
Matt Bettinelli-Olpin    1
Matt Reeves              1
Matthew O'Callaghan      1
Matthew Vaughn           1
Jon Avnet                1
Name: imdb_id, Length: 358, dtype: int64

In [147]:
answers['23']='Peter Jackson'

# 24. Какая студия дает самые длинные названия своим фильмам по количеству символов?

In [148]:
data_s24=data.copy()
data_s24['production_companies']=data_s24.production_companies.str.split('|')
data_st24=data_s24.explode('production_companies')
data_st24['original_title'] = data_st24.original_title.apply(lambda x: len(x))
data_st24.groupby('production_companies')['original_title'].mean().sort_values(ascending= False)

production_companies
Four By Two Productions       83.0
Jim Henson Company, The       59.0
Dos Corazones                 47.0
Museum Canada Productions     46.0
Polsky Films                  46.0
                              ...
Everest Entertainment          3.0
Berlanti Productions           3.0
XM2 Productions                2.0
Ixtlan Productions             2.0
Global Entertainment Group     2.0
Name: original_title, Length: 1771, dtype: float64

In [149]:
answers['24']='Four By Two Productions'

# 25. Описание фильмов какой студии в среднем самые длинные по количеству слов?

In [150]:
data_s25=data.copy()
data_s25['production_companies']=data_s25.production_companies.str.split('|')
data_st25=data_s25.explode('production_companies')
data_st25['overview']=data_st25.overview.apply(lambda x: len(x))
data_st25.groupby('production_companies')['overview'].mean().sort_values(ascending= False)

production_companies
Midnight Picture Show                    1000.0
Room 9 Entertainment                      964.0
Brookwell-McNamara Entertainment          936.0
Lions Gate Family Entertainment           909.0
Crest Animation Productions               909.0
                                          ...
Projection Pictures                        74.0
London Boulevard                           74.0
Phantom Four                               72.0
Empire Pictures                            62.0
Motion Picture Corporation of America      59.0
Name: overview, Length: 1771, dtype: float64

In [151]:
answers['25']='Midnight Picture Show'

# 26. Какие фильмы входят в 1 процент лучших по рейтингу? 
по vote_average

In [152]:
d = data['vote_average'].quantile(q=0.99, interpolation='higher')
display(d)

7.8

In [153]:
data[data['vote_average']>7.8]

,imdb_id,budget,revenue,original_title,cast,director,tagline,overview,runtime,genres,production_companies,release_date,vote_average,release_year,profit
9,tt2096673,175000000,853708609,Inside Out,Amy Poehler|Phyllis Smith|Richard Kind|Bill Ha...,Pete Docter,Meet the little voices inside your head.,"Growing up can be a bumpy road, and it's no ex...",94,Comedy|Animation|Family,Walt Disney Pictures|Pixar Animation Studios|W...,6/9/2015,8.0,2015,678708609
34,tt3170832,6000000,35401758,Room,Brie Larson|Jacob Tremblay|Joan Allen|Sean Bri...,Lenny Abrahamson,Love knows no boundaries,Jack is a young boy of 5 years old who has liv...,117,Drama|Thriller,Element Pictures|No Trace Camping|A24|Duperele...,10/16/2015,8.0,2015,29401758
118,tt0816692,165000000,621752480,Interstellar,Matthew McConaughey|Jessica Chastain|Anne Hath...,Christopher Nolan,Mankind was born on Earth. It was never meant ...,Interstellar chronicles the adventures of a gr...,169,Adventure|Drama|Science Fiction,Paramount Pictures|Legendary Pictures|Warner B...,11/5/2014,8.0,2014,456752480
119,tt2015381,170000000,773312399,Guardians of the Galaxy,Chris Pratt|Zoe Saldana|Dave Bautista|Vin Dies...,James Gunn,All heroes start somewhere.,"Light years from Earth, 26 years after being a...",121,Action|Science Fiction|Adventure,Marvel Studios|Moving Picture Company (MPC)|Bu...,7/30/2014,7.9,2014,603312399
125,tt2084970,14000000,233555708,The Imitation Game,Benedict Cumberbatch|Keira Knightley|Matthew G...,Morten Tyldum,The true enigma was the man who cracked the code.,Based on the real life story of legendary cryp...,113,History|Drama|Thriller|War,Black Bear Pictures|Bristol Automotive,11/14/2014,8.0,2014,219555708
128,tt2267998,61000000,369330363,Gone Girl,Ben Affleck|Rosamund Pike|Carrie Coon|Neil Pat...,David Fincher,You don't know what you've got 'til it's...,With his wife's disappearance having become th...,145,Mystery|Thriller|Drama,Twentieth Century Fox Film Corporation|Regency...,10/1/2014,7.9,2014,308330363
138,tt2278388,30000000,174600318,The Grand Budapest Hotel,Ralph Fiennes|Tony Revolori|F. Murray Abraham|...,Wes Anderson,A perfect holiday without leaving home.,The Grand Budapest Hotel tells of a legendary ...,99,Comedy|Drama,Fox Searchlight Pictures|Scott Rudin Productio...,2/26/2014,7.9,2014,144600318
370,tt1375666,160000000,825500000,Inception,Leonardo DiCaprio|Joseph Gordon-Levitt|Ellen P...,Christopher Nolan,Your mind is the scene of the crime.,"Cobb, a skilled thief who commits corporate es...",148,Action|Thriller|Science Fiction|Mystery|Adventure,Legendary Pictures|Warner Bros.|Syncopy,7/14/2010,7.9,2010,665500000
599,tt0468569,185000000,1001921825,The Dark Knight,Christian Bale|Michael Caine|Heath Ledger|Aaro...,Christopher Nolan,Why So Serious?,Batman raises the stakes in his war on crime. ...,152,Drama|Action|Crime|Thriller,DC Comics|Legendary Pictures|Warner Bros.|Syncopy,7/16/2008,8.1,2008,816921825
872,tt0253474,35000000,120072577,The Pianist,Adrien Brody|Thomas Kretschmann|Frank Finlay|M...,Roman Polanski,Music was his passion. Survival was his master...,The Pianist is a film adapted from the biograp...,150,Drama|War,Bac Films|Canal+Polska|Heritage Films|Studio B...,9/24/2002,7.9,2002,85072577
1081,tt0167260,94000000,1118888979,The Lord of the Rings: The Return of the King,Elijah Wood|Ian McKellen|Viggo Mortensen|Liv T...,Peter Jackson,The eye of the enemy is moving.,Aragorn is revealed as the heir to the ancient...,201,Adventure|Fantasy|Action,WingNut Films|New Line Cinema,12/1/2003,7.9,2003,1024888979
1183,tt0993846,100000000,392000694,The Wolf of Wall Street,Leonardo DiCaprio|Jonah Hill|Margot Robbie|Kyl...,Martin Scorsese,EARN. SPEND. PARTY.,A New York stockbroker refuses to cooperate in...,180,Crime|Drama|Comedy,Paramount Pictures|Appian Way|EMJAG Production...,12/25/2013,7.9,2013,292000694
1191,tt2024544,20000000,187000000,12 Years a Slave,Chiwetel Ejiofor|Michael Fassbender|Lupita Nyo...,Steve McQueen,The extraordinary true story of Solomon Northup,"In the pre-Civil War United States, Solomon No...",134,Drama|History,Plan B Entertainment|Regency Enterprises|River...,10/18/2013,7.9,2013,167000000
1800,tt0209144,9000000,39723096,Memento,Guy Pearce|Carrie-Anne Moss|Joe Pantoliano|Mar...,Christopher Nolan,Some memories are best forgotten.,Suffering short-term memory loss after a head ...,113,Mystery|Thriller,Summit Entertainment|Newmarket Capital Group|T...,10/11/2000,7.9,2000,30723096

In [154]:
#Подходит только данный вариант ответа, т.к. в других есть фильмы, которых в полученном списке нет 
answers['26']= 'Inside Out, The Dark Knight, 12 Years a Slave'

# 27. Какие актеры чаще всего снимаются в одном фильме вместе?

In [155]:
data27i=data.copy()
pairs = Counter()
for i in range(0,len(data27i)):
    artists = data27i.cast[i].split('|')
    for j in list(combinations(artists,2)):
        if j not in pairs:
            pairs[j]=1
        else:
            pairs[j]+=1
pairs.most_common(10)

[(('Daniel Radcliffe', 'Rupert Grint'), 8),
 (('Daniel Radcliffe', 'Emma Watson'), 8),
 (('Rupert Grint', 'Emma Watson'), 7),
 (('Ben Stiller', 'Owen Wilson'), 6),
 (('Johnny Depp', 'Helena Bonham Carter'), 6),
 (('Adam Sandler', 'Kevin James'), 5),
 (('Hugh Jackman', 'Ian McKellen'), 5),
 (('Kristen Stewart', 'Robert Pattinson'), 5),
 (('Kristen Stewart', 'Taylor Lautner'), 5),
 (('Robert Pattinson', 'Taylor Lautner'), 5)]

In [156]:
answers['27']='Daniel Radcliffe & Rupert Grint'

# Submission

In [157]:
# в конце можно посмотреть свои ответы к каждому вопросу
answers

{'1': '5. Pirates of the Caribbean: On Stranger Tides (tt1298650)',
 '2': 'Gods and Generals (tt0279111)',
 '3': 'Winnie the Pooh (tt1449283)',
 '4': '110',
 '5': '107',
 '6': 'Avatar (tt0499549)',
 '7': 'The Lone Ranger (tt1210819)',
 '8': '1478',
 '9': 'The Dark Knight (tt0468569)',
 '10': 'The Lone Ranger (tt1210819)',
 '11': 'Drama',
 '12': 'Drama',
 '13': 'Peter Jackson',
 '14': 'Robert Rodriguez',
 '15': 'Chris Hemsworth',
 '16': 'Matt Damon',
 '17': 'Action',
 '18': 'K-19: The Widowmaker (tt0267626)',
 '19': '2015',
 '20': '2014',
 '21': 'Сентябрь',
 '22': '450',
 '23': 'Peter Jackson',
 '24': 'Four By Two Productions',
 '25': 'Midnight Picture Show',
 '26': 'Inside Out, The Dark Knight, 12 Years a Slave',
 '27': 'Daniel Radcliffe & Rupert Grint'}

In [158]:
# и убедиться что ни чего не пропустил)
len(answers)

27